version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - rstiller
  ignore:
  - dependency-name: "@elastic/elasticsearch"
    versions:
    - "> 5.6.19, < 6"
  - dependency-name: "@elastic/elasticsearch"
    versions:
    - ">= 6.a, < 7"
  - dependency-name: "@elastic/elasticsearch"
    versions:
    - ">= 7.a, < 8"
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.1
    - 5.1.2
