{
 "title": "nodeVM-prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(process:cpu_usage, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "used heap size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(memory:usedHeapSize{application=\"express-multi-process-js\", hostname=\"$hostname\"}) by (isMaster, pid)"
    }
   ]
  },
  {
   "title": "used large object space size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(memory:spaceUsedSize{application=\"express-multi-process-js\", space=\"large_object_space\", hostname=\"$hostname\"}) by (isMaster, pid)"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "major GC runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "avg(gc:runs{application=\"express-multi-process-js\", type=\"major\", hostname=\"$hostname\"}) by (isMaster, pid)"
    }
   ]
  },
  {
   "title": "major GC runtime deviation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "stddev(gc:runs{application=\"express-multi-process-js\", type=\"major\", hostname=\"$hostname\"}) by (isMaster, pid)"
    }
   ]
  },
  { "title": "Process Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(process:cpu_usage{application=\"express-multi-process-js\", type=\"total\", hostname=\"$hostname\"} / 100000000.0) by (isMaster, pid)",
     "legendFormat": "{{isMaster}} {{pid}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "sum(eventLoop:lag{application=\"express-multi-process-js\", hostname=\"$hostname\"}) by (pid, isMaster)"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(process:active_handles{application=\"express-multi-process-js\", hostname=\"$hostname\"}) by (pid, isMaster)"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(process:active_requests{application=\"express-multi-process-js\", hostname=\"$hostname\"}) by (pid, isMaster)"
    }
   ]
  }
 ]
}