{
 "title": "nodeVM-influxdb",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "SHOW TAG VALUES FROM \"process\" WITH KEY = \"hostname\""
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "used heap size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "isMaster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"usedHeapSize.value\") AS \"used\", mean(\"totalHeapSizeExecutable.value\") AS \"executable\", mean(\"totalHeapSize.value\") AS \"total\" FROM \"memory\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "usedHeapSize.value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "used large object space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "isMaster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory",
     "query": "SELECT mean(\"usedHeapSize.value\") AS \"used\", mean(\"totalHeapSizeExecutable.value\") AS \"executable\", mean(\"totalHeapSize.value\") AS \"total\" FROM \"memory\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "spaceUsedSize.value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "space", "operator": "=", "value": "large_object_space" }
     ]
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "major GC runtime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "isMaster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gc",
     "select": [
      [
       { "params": [ "runs.mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "major" }
     ]
    }
   ]
  },
  {
   "title": "major GC runtime deviation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "isMaster" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gc",
     "select": [
      [
       { "params": [ "runs.mean" ], "type": "field" },
       {
        "params": [],
        "type": "stddev"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "major" }
     ]
    }
   ]
  },
  { "title": "Process Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "avg usage (pid $tag_pid)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process",
     "query": "SELECT moving_average(derivative(last(\"cpu_usage.count\"), 10s), 10) / 100000000 FROM \"process\" WHERE (\"hostname\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"pid\" fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage.count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "derivative" },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "lag (pid $tag_pid, master $tag_isMaster)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "isMaster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eventLoop",
     "select": [
      [
       { "params": [ "lag.value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Process Handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "active handles (pid: $tag_pid, master: $tag_isMaster)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "isMaster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process",
     "select": [
      [
       { "params": [ "active_handles.value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Process Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "active requests (pid: $tag_pid, master: $tag_isMaster)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pid" ], "type": "tag" },
      { "params": [ "isMaster" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process",
     "select": [
      [
       { "params": [ "active_requests.value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}