{
 "title": "nodeVM-carbon",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "tag_values(hostname, application=express-multi-process-js)"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "used heap size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"application=express-multi-process-js\", \"name=memory.usedHeapSize.value\") | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"heap size (master: \\1, pid: \\2)\")"
    }
   ]
  },
  {
   "title": "used large object space size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"application=express-multi-process-js\", \"name=memory.spaceUsedSize.value\", \"space=large_object_space\") | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"large object space (master: \\1, pid: \\2)\")"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "major GC runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"application=express-multi-process-js\", \"name=gc.runs.mean\", \"type=major\") | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"mean duration (master: \\1, pid: \\2)\")"
    }
   ]
  },
  {
   "title": "major GC runtime deviation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"application=express-multi-process-js\", \"name=gc.runs.mean\", \"type=major\") | stdev(5) | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"mean duration deviation (master: \\1, pid: \\2)\")"
    }
   ]
  },
  { "title": "Process Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"name=process.cpu_usage.count\", \"type=total\") | nonNegativeDerivative() | scale(0.0000001) | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"total CPU (master: \\1, pid: \\2)\")"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"name=eventLoop.lag.value\") | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"lag (master: \\1, pid: \\2)\")"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"application=express-multi-process-js\", \"name=process.active_handles.value\") | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"active handles (master: \\1, pid: \\2)\")"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "seriesByTag(\"hostname=${hostname:regex}\", \"application=express-multi-process-js\", \"name=process.active_requests.value\") | aliasSub(\".*isMaster=(true|false).*;.*pid=(\\d+);.*\", \"active requests (master: \\1, pid: \\2)\")"
    }
   ]
  }
 ]
}