version: "3"

services:

  node10:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node10
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=10

  node11:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node11
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=11

  node12:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node12
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=12

  node13:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node13
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=13

  node14:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node14
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=14

  node15:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node15
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=15

  node16:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node16
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=16

  node17:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node17
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=17

  node18:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node18
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=18

  node19:
    build:
      context: ./test-env
      dockerfile: Dockerfile-node19
    user: "root"
    entrypoint: "/opt/inspector-metrics/test-env/compile+test.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
    working_dir: "/opt/inspector-metrics"
    environment:
      - NPM_CONFIG_CACHE="/opt/inspector-metrics/.tmp/.npm/"
      - NODE_VERSION=19

  grafana:
    build:
      context: ./test-env/grafana
      args:
        TZ: Europe/Berlin
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
      - ./test-env/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./test-env/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./examples:/examples
    ports:
      - "3000:3000"
    restart: "no"
    networks:
      default:
        aliases:
         - grafana
    hostname: grafana

  graphite:
    build:
      context: ./test-env/graphite
      args:
        TZ: Europe/Berlin
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
    restart: "no"
    networks:
      default:
        aliases:
         - graphite
    hostname: graphite
  
  elasticsearch:
    build:
      context: ./test-env/elasticsearch
      args:
        TZ: Europe/Berlin
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-sSf", "http://localhost:9200"]
      interval: 5s
      timeout: 5s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 1048576
        hard: 1048576
    cap_add:
      - IPC_LOCK
    networks:
      default:
        aliases:
         - elasticsearch
    hostname: elasticsearch
    volumes:
      - ./test-env/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  
  kibana:
    build:
      context: ./test-env/kibana
      args:
        TZ: Europe/Berlin
    ports:
      - "5601:5601"
    restart: "no"
    networks:
      default:
        aliases:
         - kibana
    hostname: kibana
    volumes:
      - ./test-env/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

  influx:
    build:
      context: ./test-env/influx
      args:
        TZ: Europe/Berlin
    volumes:
      - influx-data:/var/lib/influxdb
      - influx-logs:/var/log/influxdb
    ports:
      - "8086:8086"
    restart: "no"
    networks:
      default:
        aliases:
         - influx
    hostname: influx

  influx-v2:
    build:
      context: ./test-env/influx-v2
      args:
        TZ: Europe/Berlin
    command: ["--reporting-disabled"]
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=testing
      - DOCKER_INFLUXDB_INIT_BUCKET=test-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=che2u4kqsajBirtunseKpCOX0Z4sebMB6JEzibbc3prOyyAkzdMCfFLgQhVqRUgQRlAlyKz8PlWq-Z2NhAVkNw==
    volumes:
      - influx-v2-data:/var/lib/influxdb2
      - influx-v2-logs:/var/log/influxdb2
    ports:
      - "8087:8087"
    restart: "no"
    networks:
      default:
        aliases:
         - influx-v2
    hostname: influx-v2

  pushgateway:
    build:
      context: ./test-env/pushgateway
      args:
        TZ: CET-1CEST
    ports:
      - "9091:9091"
    restart: "no"
    networks:
      default:
        aliases:
         - pushgateway
    hostname: pushgateway

  prometheus:
    build:
      context: ./test-env/prometheus
      args:
        TZ: CET-1CEST
    command: [
                "--config.file", "/etc/prometheus/config.yml",
                "--storage.tsdb.path", "/prometheus-data"
             ]
    ports:
      - "9090:9090"
    restart: "no"
    networks:
      default:
        aliases:
         - prometheus
    hostname: prometheus
    volumes:
      - prometheus-data:/prometheus-data
      - ./test-env/prometheus/config.yml:/etc/prometheus/config.yml

  docs:
    build:
      context: ./test-env/node-dev
      args:
        TZ: Europe/Berlin
    entrypoint: bash
    command:
      - "build-docs.sh"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
      - ./test-env/node-dev/build-docs.sh:/usr/bin/build-docs.sh
      - pnpm-store:/root/.pnpm-store
    working_dir: "/opt/inspector-metrics"

  deps:
    build:
      context: ./test-env/node-dev
      args:
        TZ: Europe/Berlin
    entrypoint: bash
    command:
      - "-c"
      - "npm run deps"
    restart: "no"
    volumes:
      - .:/opt/inspector-metrics/
      - pnpm-store:/root/.pnpm-store
    working_dir: "/opt/inspector-metrics"

volumes:
  grafana-data:
  grafana-logs:
  influx-data:
  influx-logs:
  influx-v2-data:
  influx-v2-logs:
  prometheus-data:
  pnpm-store:
