apiVersion: 1

# see http://docs.grafana.org/administration/provisioning/
datasources:
- name: graphite
  type: graphite
  access: proxy
  url: http://graphite/
  isDefault: false
  editable: true
  jsonData:
    graphiteVersion: "1.1"
- name: prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: false
  editable: true
- name: influxdb-express-multi-process-js
  type: influxdb
  access: proxy
  url: http://influx:8086
  isDefault: false
  editable: true
  database: express-multi-process-js
  user: admin
  password: admin
- name: influxdb-v1-example
  type: influxdb
  access: proxy
  url: http://influx:8086
  isDefault: false
  editable: false
  database: influx-v1-example
  user: admin
  password: admin
- name: influxdb-v2-example
  access: "proxy"
  jsonData:
    defaultBucket: "test-bucket"
    httpMode: "POST"
    organization: "testing"
    version: "Flux"
  secureJsonData:
    token: "che2u4kqsajBirtunseKpCOX0Z4sebMB6JEzibbc3prOyyAkzdMCfFLgQhVqRUgQRlAlyKz8PlWq-Z2NhAVkNw=="
  type: influxdb
  url: "http://influx-v2:8087"
- name: elasticsearch-express-multi-process-js
  type: elasticsearch
  access: proxy
  isDefault: false
  editable: true
  database: "[metric-express-multi-process-js-]YYYY-MM-DD"
  url: http://elasticsearch:9200
  jsonData:
    interval: Daily
    timeField: "timestamp"
- name: elasticsearch-5
  type: elasticsearch
  access: proxy
  isDefault: false
  editable: true
  database: "[metric-elasticsearch-5-]YYYY-MM-DD"
  url: http://elasticsearch:9200
  jsonData:
    interval: Daily
    timeField: "timestamp"
- name: elasticsearch-6
  type: elasticsearch
  access: proxy
  isDefault: false
  editable: true
  database: "[metric-elasticsearch-6-]YYYY-MM-DD"
  url: http://elasticsearch:9200
  jsonData:
    interval: Daily
    timeField: "timestamp"
- name: elasticsearch-7
  type: elasticsearch
  access: proxy
  isDefault: false
  editable: true
  database: "[metric-elasticsearch-7-]YYYY-MM-DD"
  url: http://elasticsearch:9200
  jsonData:
    interval: Daily
    timeField: "timestamp"
