{
 "title": "nodeVM-elasticsearch-5",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "{\"find\": \"terms\", \"field\": \"tags.hostname.keyword\", \"query\": \"\"}"
   }
  ]
 },
 "panels": [
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "used heap size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used size (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "group: \"memory\" AND name: \"usedHeapSize\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "large object space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "used space (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.value",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "group: \"memory\" AND name: \"spaceUsedSize\" AND tags.scope: \"large_object_space\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "major GC runtime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "mean (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.mean",
       "id": "1",
       "inlineScript": null,
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "group: \"gc\" AND name: \"runs\" AND tags.type: \"major\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "major GC runtime stddev",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "mean stddev (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.stddev",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "group: \"gc\" AND name: \"runs\" AND tags.type: \"major\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Process Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "CPU Usage (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.count",
       "hide": true,
       "id": "1",
       "inlineScript": "_value * 0.00000001",
       "meta": {},
       "pipelineAgg": "select metric",
       "settings": { "script": { "inline": "_value * 0.00000001" } },
       "type": "avg"
      },
      {
       "field": "1",
       "id": "7",
       "meta": {},
       "pipelineAgg": "1",
       "settings": {},
       "type": "derivative"
      }
     ],
     "query": "group: \"process\" AND name: \"cpu_usage\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "lag (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "group: \"eventLoop\" AND name: \"lag\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active Handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "active handles (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "group: \"process\" AND name: \"active_handles\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "active requests (pid: {{term tags.pid.keyword}})",
     "bucketAggs": [
      {
       "fake": true,
       "field": "tags.pid.keyword",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "timestamp",
       "id": "5",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "field": "values.value",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "group: \"process\" AND name: \"active_requests\" AND tags.hostname: \"$hostname\" AND tags.application: \"elasticsearch-5\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}