name: CI

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 17.x, 18.x, 19.x]
        os:
          #- windows-2022
          #- windows-2019
          #- macos-12
          #- macos-11
          - ubuntu-22.04
          - ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ runner.node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.node-version }}-build-${{ env.cache-name }}-

      - uses: pnpm/action-setup@v2
        with:
          version: 6
          dest: ~/.pnpm-store
          run_install: |
            - args: [--global, rimraf, node-gyp]
            - recursive: true

      - name: build
        run: pnpm run build

      - name: test
        run: pnpm run test
        env:
          CI: true
          TZ: Europe/Berlin
